"""initial schema

Revision ID: a1421c7ab529
Revises:
Create Date: 2026-05-11 03:30:54.521038

"""

from typing import Sequence, Union

import sqlalchemy as sa

import airdrome.models
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a1421c7ab529"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apple_ms_playlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("container_identifier", sa.BIGINT(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("container_type", sa.String(), nullable=False),
        sa.Column("parent_folder_identifier", sa.BIGINT(), nullable=True),
        sa.Column("date_added", sa.DateTime(timezone=True), nullable=True),
        sa.Column("items_modified_date", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("container_identifier"),
    )
    op.create_table(
        "appleplaylist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("persistent_id", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("all_items", sa.Boolean(), nullable=False),
        sa.Column("parent_persistent_id", sa.String(), nullable=True),
        sa.Column("master", sa.Boolean(), nullable=False),
        sa.Column("visible", sa.Boolean(), nullable=False),
        sa.Column("music", sa.Boolean(), nullable=False),
        sa.Column("folder", sa.Boolean(), nullable=False),
        sa.Column("distinguished_kind", sa.Integer(), nullable=True),
        sa.Column("favorited", sa.Boolean(), nullable=False),
        sa.Column("loved", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("persistent_id"),
        sa.UniqueConstraint("playlist_id"),
    )
    op.create_table(
        "playlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "platform",
            sa.Enum("SPOTIFY", "LASTFM", "APPLE", "LISTENBRAINZ", "NAVIDROME", name="platform"),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("date_added", sa.DateTime(timezone=True), nullable=True),
        sa.Column("date_modified", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "track",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("artist", sa.String(), nullable=True),
        sa.Column("album_artist", sa.String(), nullable=True),
        sa.Column("album", sa.String(), nullable=True),
        sa.Column("track_n", sa.Integer(), nullable=True),
        sa.Column("disc_n", sa.Integer(), nullable=True),
        sa.Column("compilation", sa.Boolean(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("date_added", sa.DateTime(timezone=True), nullable=False),
        sa.Column("loved", sa.Boolean(), nullable=True),
        sa.Column("album_loved", sa.Boolean(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("album_rating", sa.Integer(), nullable=True),
        sa.Column("title_norm", sa.String(), nullable=False),
        sa.Column("artist_norm", sa.String(), nullable=False),
        sa.Column("album_artist_norm", sa.String(), nullable=False),
        sa.Column("album_norm", sa.String(), nullable=False),
        sa.Column("canon_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["canon_id"], ["track.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title", "artist", "album", "album_artist"),
    )
    op.create_index(
        "ix_track_album_artist_norm_trgm",
        "track",
        ["album_artist_norm"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"album_artist_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("album_artist_norm <> ''"),
    )
    op.create_index(
        "ix_track_album_norm_trgm",
        "track",
        ["album_norm"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"album_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("album_norm <> ''"),
    )
    op.create_index(
        "ix_track_artist_norm_trgm",
        "track",
        ["artist_norm"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"artist_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("artist_norm <> ''"),
    )
    op.create_index(op.f("ix_track_canon_id"), "track", ["canon_id"], unique=False)
    op.create_index(
        "ix_track_title_norm_trgm",
        "track",
        ["title_norm"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title_norm": "gin_trgm_ops"},
    )
    op.create_table(
        "apple_ms_track",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=True),
        sa.Column("track_identifier", sa.BIGINT(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("artist", sa.String(), nullable=True),
        sa.Column("album", sa.String(), nullable=True),
        sa.Column("album_artist", sa.String(), nullable=True),
        sa.Column("compilation", sa.Boolean(), nullable=False),
        sa.Column("track_number", sa.Integer(), nullable=True),
        sa.Column("disc_number", sa.Integer(), nullable=True),
        sa.Column("track_count", sa.Integer(), nullable=True),
        sa.Column("disc_count", sa.Integer(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("play_count", sa.Integer(), nullable=True),
        sa.Column("skip_count", sa.Integer(), nullable=True),
        sa.Column("date_added", sa.DateTime(timezone=True), nullable=True),
        sa.Column("date_modified", sa.DateTime(timezone=True), nullable=True),
        sa.Column("release_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("genre", sa.String(), nullable=True),
        sa.Column("audio_file_extension", sa.String(), nullable=True),
        sa.Column("is_purchased", sa.Boolean(), nullable=False),
        sa.Column("purchased_track_identifier", sa.BIGINT(), nullable=True),
        sa.Column("audio_matched_track_identifier", sa.BIGINT(), nullable=True),
        sa.ForeignKeyConstraint(["track_id"], ["track.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("track_identifier"),
    )
    op.create_table(
        "appletrack",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=True),
        sa.Column("apple_track_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("album", sa.String(), nullable=True),
        sa.Column("artist", sa.String(), nullable=True),
        sa.Column("album_artist", sa.String(), nullable=True),
        sa.Column("apple_music", sa.Boolean(), nullable=False),
        sa.Column("compilation", sa.Boolean(), nullable=True),
        sa.Column("track_number", sa.Integer(), nullable=True),
        sa.Column("disc_number", sa.Integer(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("release_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("loved", sa.Boolean(), nullable=False),
        sa.Column("favorited", sa.Boolean(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("rating_computed", sa.Boolean(), nullable=False),
        sa.Column("album_loved", sa.Boolean(), nullable=False),
        sa.Column("album_rating", sa.Integer(), nullable=True),
        sa.Column("album_rating_computed", sa.Boolean(), nullable=False),
        sa.Column("date_added", sa.DateTime(timezone=True), nullable=False),
        sa.Column("date_modified", sa.DateTime(timezone=True), nullable=False),
        sa.Column("play_date_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("play_date", sa.BIGINT(), nullable=True),
        sa.Column("total_time", sa.Integer(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column(
            "track_type",
            sa.Enum("URL", "Remote", "File", name="tracktype", native_enum=False),
            nullable=False,
        ),
        sa.Column("persistent_id", sa.String(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("MPEG4_AUDIO", "AAC_BOUGHT", "MPEG_AUDIO", "AAC", "AAC_AM", "MPEG4_VIDEO", name="kind"),
            nullable=True,
        ),
        sa.Column("grouping", sa.String(), nullable=True),
        sa.Column("genre", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("bit_rate", sa.Integer(), nullable=True),
        sa.Column("sample_rate", sa.Integer(), nullable=True),
        sa.Column("bpm", sa.Integer(), nullable=True),
        sa.Column("normalization", sa.Integer(), nullable=True),
        sa.Column("volume_adjustment", sa.Integer(), nullable=True),
        sa.Column("play_count", sa.Integer(), nullable=True),
        sa.Column("skip_count", sa.Integer(), nullable=True),
        sa.Column("skip_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disliked", sa.Boolean(), nullable=False),
        sa.Column("comments", sa.String(), nullable=True),
        sa.Column("sort_name", sa.String(), nullable=True),
        sa.Column("sort_artist", sa.String(), nullable=True),
        sa.Column("sort_album_artist", sa.String(), nullable=True),
        sa.Column("sort_album", sa.String(), nullable=True),
        sa.Column("sort_composer", sa.String(), nullable=True),
        sa.Column("work", sa.String(), nullable=True),
        sa.Column("composer", sa.String(), nullable=True),
        sa.Column("movement_name", sa.String(), nullable=True),
        sa.Column("movement_count", sa.Integer(), nullable=True),
        sa.Column("disc_count", sa.Integer(), nullable=True),
        sa.Column("track_count", sa.Integer(), nullable=True),
        sa.Column("artwork_count", sa.Integer(), nullable=True),
        sa.Column("file_folder_count", sa.Integer(), nullable=True),
        sa.Column("library_folder_count", sa.Integer(), nullable=True),
        sa.Column("protected", sa.Boolean(), nullable=False),
        sa.Column("music_video", sa.Boolean(), nullable=False),
        sa.Column("has_video", sa.Boolean(), nullable=False),
        sa.Column("part_of_gapless_album", sa.Boolean(), nullable=True),
        sa.Column("playlist_only", sa.Boolean(), nullable=False),
        sa.Column("purchased", sa.Boolean(), nullable=False),
        sa.Column("matched", sa.Boolean(), nullable=False),
        sa.Column("explicit", sa.Boolean(), nullable=False),
        sa.Column("clean", sa.Boolean(), nullable=False),
        sa.Column("hd", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["track_id"], ["track.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("apple_track_id"),
        sa.UniqueConstraint("persistent_id"),
    )
    op.create_table(
        "playlistlink",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("backend", sa.Enum("NAVIDROME", name="backend"), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("synced_track_ids", sa.JSON(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["playlist_id"], ["playlist.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("backend", "external_id"),
        sa.UniqueConstraint("playlist_id", "backend"),
    )
    op.create_index(op.f("ix_playlistlink_playlist_id"), "playlistlink", ["playlist_id"], unique=False)
    op.create_table(
        "playlisttrack",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["playlist_id"], ["playlist.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["track_id"], ["track.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("playlist_id", "track_id"),
    )
    op.create_index(op.f("ix_playlisttrack_playlist_id"), "playlisttrack", ["playlist_id"], unique=False)
    op.create_index(op.f("ix_playlisttrack_position"), "playlisttrack", ["position"], unique=False)
    op.create_index(op.f("ix_playlisttrack_track_id"), "playlisttrack", ["track_id"], unique=False)
    op.create_table(
        "trackalias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("artist", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("album", sa.String(), nullable=True),
        sa.Column("artist_norm", sa.String(), nullable=False),
        sa.Column("title_norm", sa.String(), nullable=False),
        sa.Column("album_norm", sa.String(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["track.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title", "album", "artist"),
    )
    op.create_index(
        "ix_trackalias_album_norm_trgm",
        "trackalias",
        ["album_norm"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"album_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("album_norm <> ''"),
    )
    op.create_index(
        "ix_trackalias_artist_norm_trgm",
        "trackalias",
        ["artist_norm"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"artist_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("artist_norm <> ''"),
    )
    op.create_index(
        "ix_trackalias_title_norm_trgm",
        "trackalias",
        ["title_norm"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title_norm": "gin_trgm_ops"},
    )
    op.create_index(op.f("ix_trackalias_track_id"), "trackalias", ["track_id"], unique=False)
    op.create_table(
        "trackfile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_path", airdrome.models.PathType(), nullable=False),
        sa.Column("library_path", airdrome.models.PathType(), nullable=True),
        sa.Column("is_main", sa.Boolean(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("bitrate", sa.Integer(), nullable=True),
        sa.Column("date", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("artist", sa.String(), nullable=True),
        sa.Column("album_artist", sa.String(), nullable=True),
        sa.Column("album", sa.String(), nullable=True),
        sa.Column("title_norm", sa.String(), nullable=False),
        sa.Column("artist_norm", sa.String(), nullable=False),
        sa.Column("album_artist_norm", sa.String(), nullable=False),
        sa.Column("album_norm", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["track_id"], ["track.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("library_path"),
        sa.UniqueConstraint("source_path"),
    )
    op.create_index(
        "ix_trackfile_album_artist_norm_trgm",
        "trackfile",
        ["album_artist_norm"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"album_artist_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("album_artist_norm <> ''"),
    )
    op.create_index(
        "ix_trackfile_album_norm_trgm",
        "trackfile",
        ["album_norm"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"album_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("album_norm <> ''"),
    )
    op.create_index(
        "ix_trackfile_artist_norm_trgm",
        "trackfile",
        ["artist_norm"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"artist_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("artist_norm <> ''"),
    )
    op.create_index(
        "ix_trackfile_title_norm_trgm",
        "trackfile",
        ["title_norm"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title_norm": "gin_trgm_ops"},
    )
    op.create_index(op.f("ix_trackfile_track_id"), "trackfile", ["track_id"], unique=False)
    op.create_table(
        "apple_ms_playlist_track",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["playlist_id"], ["apple_ms_playlist.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["track_id"], ["apple_ms_track.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_apple_ms_playlist_track_playlist_id"),
        "apple_ms_playlist_track",
        ["playlist_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_apple_ms_playlist_track_position"), "apple_ms_playlist_track", ["position"], unique=False
    )
    op.create_index(
        op.f("ix_apple_ms_playlist_track_track_id"), "apple_ms_playlist_track", ["track_id"], unique=False
    )
    op.create_table(
        "appleplaylisttrack",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["playlist_id"], ["appleplaylist.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["track_id"], ["appletrack.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_appleplaylisttrack_playlist_id"), "appleplaylisttrack", ["playlist_id"], unique=False
    )
    op.create_index(op.f("ix_appleplaylisttrack_position"), "appleplaylisttrack", ["position"], unique=False)
    op.create_index(op.f("ix_appleplaylisttrack_track_id"), "appleplaylisttrack", ["track_id"], unique=False)
    op.create_table(
        "trackaliasscrobble",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alias_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "platform",
            sa.Enum("SPOTIFY", "LASTFM", "APPLE", "LISTENBRAINZ", "NAVIDROME", name="platform"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["alias_id"], ["trackalias.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date"),
    )
    op.create_index(op.f("ix_trackaliasscrobble_alias_id"), "trackaliasscrobble", ["alias_id"], unique=False)
    op.create_table(
        "trackplay",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("played_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "platform",
            sa.Enum("SPOTIFY", "LASTFM", "APPLE", "LISTENBRAINZ", "NAVIDROME", name="platform"),
            nullable=False,
        ),
        sa.Column("source_scrobble_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["source_scrobble_id"], ["trackaliasscrobble.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["track_id"], ["track.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_scrobble_id"),
        sa.UniqueConstraint("track_id", "played_at"),
    )
    op.create_index(op.f("ix_trackplay_track_id"), "trackplay", ["track_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trackplay_track_id"), table_name="trackplay")
    op.drop_table("trackplay")
    op.drop_index(op.f("ix_trackaliasscrobble_alias_id"), table_name="trackaliasscrobble")
    op.drop_table("trackaliasscrobble")
    op.drop_index(op.f("ix_appleplaylisttrack_track_id"), table_name="appleplaylisttrack")
    op.drop_index(op.f("ix_appleplaylisttrack_position"), table_name="appleplaylisttrack")
    op.drop_index(op.f("ix_appleplaylisttrack_playlist_id"), table_name="appleplaylisttrack")
    op.drop_table("appleplaylisttrack")
    op.drop_index(op.f("ix_apple_ms_playlist_track_track_id"), table_name="apple_ms_playlist_track")
    op.drop_index(op.f("ix_apple_ms_playlist_track_position"), table_name="apple_ms_playlist_track")
    op.drop_index(op.f("ix_apple_ms_playlist_track_playlist_id"), table_name="apple_ms_playlist_track")
    op.drop_table("apple_ms_playlist_track")
    op.drop_index(op.f("ix_trackfile_track_id"), table_name="trackfile")
    op.drop_index(
        "ix_trackfile_title_norm_trgm",
        table_name="trackfile",
        postgresql_using="gin",
        postgresql_ops={"title_norm": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_trackfile_artist_norm_trgm",
        table_name="trackfile",
        postgresql_using="gin",
        postgresql_ops={"artist_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("artist_norm <> ''"),
    )
    op.drop_index(
        "ix_trackfile_album_norm_trgm",
        table_name="trackfile",
        postgresql_using="gin",
        postgresql_ops={"album_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("album_norm <> ''"),
    )
    op.drop_index(
        "ix_trackfile_album_artist_norm_trgm",
        table_name="trackfile",
        postgresql_using="gin",
        postgresql_ops={"album_artist_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("album_artist_norm <> ''"),
    )
    op.drop_table("trackfile")
    op.drop_index(op.f("ix_trackalias_track_id"), table_name="trackalias")
    op.drop_index(
        "ix_trackalias_title_norm_trgm",
        table_name="trackalias",
        postgresql_using="gin",
        postgresql_ops={"title_norm": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_trackalias_artist_norm_trgm",
        table_name="trackalias",
        postgresql_using="gin",
        postgresql_ops={"artist_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("artist_norm <> ''"),
    )
    op.drop_index(
        "ix_trackalias_album_norm_trgm",
        table_name="trackalias",
        postgresql_using="gin",
        postgresql_ops={"album_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("album_norm <> ''"),
    )
    op.drop_table("trackalias")
    op.drop_index(op.f("ix_playlisttrack_track_id"), table_name="playlisttrack")
    op.drop_index(op.f("ix_playlisttrack_position"), table_name="playlisttrack")
    op.drop_index(op.f("ix_playlisttrack_playlist_id"), table_name="playlisttrack")
    op.drop_table("playlisttrack")
    op.drop_index(op.f("ix_playlistlink_playlist_id"), table_name="playlistlink")
    op.drop_table("playlistlink")
    op.drop_table("appletrack")
    op.drop_table("apple_ms_track")
    op.drop_index(
        "ix_track_title_norm_trgm",
        table_name="track",
        postgresql_using="gin",
        postgresql_ops={"title_norm": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_track_canon_id"), table_name="track")
    op.drop_index(
        "ix_track_artist_norm_trgm",
        table_name="track",
        postgresql_using="gin",
        postgresql_ops={"artist_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("artist_norm <> ''"),
    )
    op.drop_index(
        "ix_track_album_norm_trgm",
        table_name="track",
        postgresql_using="gin",
        postgresql_ops={"album_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("album_norm <> ''"),
    )
    op.drop_index(
        "ix_track_album_artist_norm_trgm",
        table_name="track",
        postgresql_using="gin",
        postgresql_ops={"album_artist_norm": "gin_trgm_ops"},
        postgresql_where=sa.text("album_artist_norm <> ''"),
    )
    op.drop_table("track")
    op.drop_table("playlist")
    op.drop_table("appleplaylist")
    op.drop_table("apple_ms_playlist")
    # ### end Alembic commands ###
